# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/isdebesl/projek-kelompok-5-orbit/blob/main/Ngorbit.ipynb

# Memuat Drive
""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/GitHub/projek-kelompok-5-orbit

"""# Mengimport library yang dibutuhkan"""

import os
import keras
from keras.preprocessing import image
from keras.applications.imagenet_utils import decode_predictions, preprocess_input
from keras.applications.vgg19 import VGG19, preprocess_input
from keras.models import Model
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from scipy.spatial import distance
import pickle
import random
import pathlib

"""# Menginput model Pre-Train VGG19

"""

candi = {
    'candi_arca_gupolo': ['Candi Arca Gupolo', 'Sambi Rejo , Prambanan , Sleman , Daerah Istimewa Yogyakarta 55572 Madurejo Daerah Istimewa Yogyakarta', 'Buka 24 Jam', 4.3,'Budaya peninggalan hindu di dukuh gunung sari Desa sambirejo','./img/candi/arcagupolo.jpg'],
    'candi_bahal': ['Candi Bahal', 'Desa Bahal, Padang Bolak, Sibatu Loting, Kec. Barumun Tengah, Kabupaten Padang Lawas Utara, Sumatera Utara 22741, Indonesia', 'Setiap Hari 06.00-18.00',4.2 ,'Sejarah bangsa ada disini','./img/candi/bahal.JPG'],
    'candi_banyunibo': ['Candi Banyunibo', 'Cepit, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572, Indonesia', 'Setiap Hari  06.00 – 17.00', 4.5,'Selain wisata budaya, anak atau keluarga dapat dikenalkan dengan alam.','./img/candi/banyunibo.jpg'],
    'candi_borobudur': ['Candi Borobudur', 'Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Kec. Borobudur, Kabupaten Magelang, Jawa Tengah.', 'Setiap Hari, 06:30 - 16:30', 4.5 ,'Tempat wisata, belajar sejarah, juga terdapat pasar untuk berbelanja buah tangan','./img/candi/borobudur.jpg'],
    'candi_brahu': ['Candi Brahu', ' Jl. Candi Brahu No.73, Siti Inggil, Bejijong, Kec. Trowulan, Kabupaten Mojokerto, Jawa Timur 61362, Indonesia', 'Setiap Hari  06.00 – 18.00', 4.6 ,'Sejarah anyaman terbentunya Generasi Bangsa dan Tanah Air.','./img/candi/brahu.jpg'],
    'candi_cangkuang': ['Candi Cangkuang', 'Jalan Darajat Leuwigoong, Cangkuang, Kec. Leles, Kabupaten Garut, Jawa Barat 44119, Indonesia', 'Setiap Hari  07.30 – 17.00', 4.4,'Fasilitas bagooss, suasana adeem, bagus buat edukasi tentang sejarah','./img/candi/cangkuang.jpg'],
    'candi_cetho': ['Candi Cetho', 'Dukuh, Cetho, Gumeng, Kec. Jenawi, Kabupaten Karanganyar, Jawa Tengah 57794, Indonesia', 'Setiap Hari  08.00 – 17.00', 4.7 ,'Buat yg suka pemandangan situs sejarah diatasi bukit bisa jadi rekomendasi nih','./img/candi/cetho.jpg'],
    'candi_dieng': ['Candi Dieng', 'Dataran Tinggi Dieng, Kabupaten Banjarnegara, Jawa Tengah, Indonesia', 'Buka 24 Jam', 4.6,'Candi peninggalan sejarah, yg sering digunakan utuk upacara adat di Dieng','./img/candi/dieng.jpg'],
    'candi_gedong_songo': ['Candi Gedong Songo', 'Jalan Ke Candi Gedong Songo, Candi, Krajan, Banyukuning, Bandungan, Kabupaten Semarang, Jawa Tengah 50614, Indonesia', 'Setiap hari  07.00 – 17.00', 4.5,'Mantab untuk belajar seJarah, bisa sewa kuda kaya orang jaman dulu.','./img/candi/gedongsongo.jpg'],
    'candi_gunung_sari': ['Candi Gunung Sari', ' Gunungsari, Gulon, Salam, Kuncen, Seloboro, Kec. Salam, Kabupaten Magelang, Jawa Tengah 56484, Indonesia', 'Setiap hari  07.00 – 17.00', 4.3 ,'"Candinya di atas bukit, jalan masuknya melewati pemakaman umum dan hutan bambu."','./img/candi/gunungsari.jpg'],
    'candi_gunung_wukir': ['Candi Gunung Wukir', 'Canggal, Kadiluwih, Salam, Area Kebun, Kadiluwih, Kec. Salam, Kabupaten Magelang, Jawa Tengah 56484, Indonesia', 'Setiap hari  08.00 – 17.00', 4.4 ,'Candi yg terletak di atas bukit ,suasana sepi melintasi hutan bambu','./img/candi/gunungwukir.jpg'],
    'candi_jabung': ['Candi Jabung', 'Dusun Candi, Jabung Candi, Kec. Paiton, Kabupaten Probolinggo, Jawa Timur 67291, Indonesia', 'Setiap Hari  06.00 – 18.00', 4.4 ,'Semoga ada fasilitas untuk cuci tangan agar pengunjung bisa mengikuti prokes.','./img/candi/jabung.jpg'],
    'candi_jago': ['Candi Jago', ' Jl. Wisnuwardhana, Ronggowuni, Tumpang, Kec. Tumpang, Kabupaten Malang, Jawa Timur 65156, Indonesia', 'Setiap Hari  07.30 – 16.00', 4.6 ,'Cagar budaya daerah tumpang, kebersihan taman okay, toilet kurang bersih','./img/candi/jago.jpg'],
    'candi_kalasan': ['Candi Kalasan', ' Jl. Raya Yogya - Solo, Suryatmajan, Danurejan, Daerah Istimewa Yogyakarta, Indonesia', 'Setiap hari  07.00 – 17.00', 4.5,'Mahakarya masyarakat indonesia jaman dulu Semoga tetap terjaga kelestarianya','./img/candi/kalasan.jpg'],
    'candi_mendut': ['Candi Mendut', 'Jl. Mayor Kusen, Sumberrejo, Mendut, Kec. Mungkid, Kabupaten Magelang, Jawa Tengah 56501, Indonesia', 'Setiap hari  07.00 – 19.00', 4.6,'Candi dengan taman yang bagus..ngopi di bawah pohon suasana santai','./img/candi/mendut.jpg'],
    'candi_muara_takus': ['Candi Muara Takus', 'Muara Takus, Kec. XIII Koto Kampar, Kabupaten Kampar, Riau 28453, Indonesia', 'Setiap Hari  08.00 – 18.00', 4.3,'Ini memandakan bahwa jauh sebelum Islam ada di Riau, ada umat hindu/ budha"','./img/candi/muaratakus.jpg'],
    'candi_muaro_jambi': ['Candi Muaro Jambi', 'Muaro Jambi, Kec. Maro Sebo, Kabupaten Muaro Jambi, Jambi 36382, Indonesia', 'Setiap Hari  08.00 – 18.00', 4.5,'Tempat wisata cagar alam yang bagus untuk dikunjungi di muara Jambi (Kota Jambi)','./img/candi/muarojambi.jpg'],
    'candi_pawon': ['Candi Pawon', 'Brojonalan, Dusun 1, Wanurejo, Kec. Borobudur, Kabupaten Magelang, Jawa Tengah 56553, Indonesia', 'Setiap Hari  09.00–17.30', 4.4 ,'Eksotis sekali Candinya, memperlihatkan kesempurnaan Peradaban Leluhur Nusantara pada eranya. Nuansa klasiknya terasa sekali, terlihat di reliefnya.','./img/candi/pawon.jpg'],
    'candi_penataran': ['Candi Penataran', 'Penataran, Kec. Nglegok, Kabupaten Blitar, Jawa Timur 66181, Indonesia', 'Setiap Hari  08.00 – 17.00', 4.5,'Tempat wisata sejarah bangsa Indonesia yg bagus yg ada di Blitar.','./img/candi/penataran.jpg'],
    'candi_plaosan': ['Candi Plaosan', ' Jl. Candi Plaosan, Plaosan Lor, Bugisan, Kec. Prambanan, Kabupaten Klaten, Jawa Tengah 57454, Indonesia', 'Setiap Hari  08.00 – 16.00', 4.6,'Situs warisan budaya berupa candi Hindu-Buddha di Jawa.','./img/candi/plaosan.jpg'],
    'candi_prambanan': ['Candi Prambanan', ' Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55571, Indonesia', 'Setiap Hari  06.30 – 17.00', 4.7,'Tempat wisata yang bagus untuk belajar sejarah agama Hindu di Indonesia.','./img/candi/prambanan.jpg'],
    'candi_ratu_boko': ['Candi Ratu Boko', ' Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 5572, Indonesia', 'Setiap Hari  08.00 – 17.00', 4.6,'Yg doyan olahraga bisa juga nih lewat belakang jalur bis/mobil hehe','./img/candi/ratuboko.jpg'],
    'candi_sambisari': ['Candi Sambisari', 'Jl. Candi Sambisari, Sambisari, Purwomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55571, Indonesia', 'Setiap hari  07.00 – 17.00', 4.6,'Bagus untuk pengetahuan sejarah dan budaya leluhur Bangsa Indonesia.','./img/candi/sambisari.jpg'],
    'candi_sewu': ['Candi Sewu', 'Jl. Raya Solo - Yogyakarta No.KM.16, Bugisan, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Indonesia', 'Setiap hari  06.00 – 17.00', 4.6 ,'Sangat bagus untuk wisata dan belajar sejarah dan budaya','./img/candi/sewu.jpg'],
    'candi_sukuh': ['Candi Sukuh', ' Tambak, Berjo, Kec. Ngargoyoso, Kabupaten Karanganyar, Jawa Tengah 57793, Indonesia', 'Setiap hari  07.00 – 15.00', 4.6,'Tujuan wisata yg asri dan suasana yg adem krna posisi di kaki gunung lawu','./img/candi/sukuh.jpg']
    
        }


model = keras.applications.vgg19.VGG19(weights='imagenet', include_top=True)

images_path = './dataset'
image_extensions = ['.jpg', '.png', '.jpeg']   # case-insensitive (upper/lower doesn't matter)
max_num_images = 10000

images = [os.path.join(dp, f) for dp, dn, filenames in os.walk(images_path) for f in filenames if os.path.splitext(f)[1].lower() in image_extensions]
if max_num_images < len(images):
    images = [images[i] for i in sorted(random.sample(xrange(len(images)), max_num_images))]

def load_image(path):
    img = image.load_img(path, target_size=model.input_shape[1:3])
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    return img, x

feat_extractor = Model(inputs=model.input, outputs=model.get_layer("fc2").output)
feat_extractor.summary()

"""# Modelling"""

pick = open('features.p', 'rb')
data = pickle.load(pick)
pick.close()
def get_concatenated_images(indexes, thumb_height):
    thumbs = []
    labels = []
    for idx in indexes:
        img = image.load_img(images[idx])
        path = pathlib.PurePath(images[idx])
        #print(path.parent.name)
        img = img.resize((int(img.width * thumb_height / img.height), thumb_height))
        thumbs.append(img)
        labels.append(path.parent.name)
    concat_image = np.concatenate([np.asarray(t) for t in thumbs], axis=1)
    return concat_image, labels

def most_frequent(List):
    return max(set(List), key = List.count)


def predict(image_path):
    new_image, x = load_image(image_path)
    new_features = feat_extractor.predict(x)

    # project it into pca space
    new_pca_features = data[2].transform(new_features)[0]

    # calculate its distance to all the other images pca feature vectors
    distances = [ distance.cosine(new_pca_features, feat) for feat in data[1] ]
    idx_closest = sorted(range(len(distances)), key=lambda k: distances[k])[0:7]  # grab first 5
    results_image, labels = get_concatenated_images(idx_closest, 200)
    candi_predict = most_frequent(labels)
    candi_data = candi[candi_predict]
    return candi_data